### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by lzaya** [KKsimi/StoHisNet#1]
I attempt to get the dataset you mentioned in your paper, but the download link has expired. Could you share the gastric histopathology data of "SEED"? Thanks a lot. QAQ

**Comment by DriveNU** [comment]
Have the dataset been shared? I would like to download it too.

**Comment by KKsimi** [comment]
I'm very sorry for the delayed response. For dataset requests, you can only apply through the provided link; we don't have the authority to provide it directly.

**Comment by KKsimi** [comment]
> I attempt to get the dataset you mentioned in your paper, but the download link has expired. Could you share the gastric histopathology data of "SEED"? Thanks a lot. QAQ

I'm very sorry for the delayed response. For dataset requests, you can only apply through the provided link; we don't have the authority to provide it directly.
